version: '3.8'

services:
  db-immo:
    image: postgres:15-alpine
    container_name: azur_db
    environment:
      POSTGRES_USER: co_lelong
      POSTGRES_PASSWORD: Clelong@Post.2026
      POSTGRES_DB: azurimmo
    volumes:
      - azur_data:/var/lib/postgresql/data
    networks:
      - immo_network

  back-immo:
    build:
      context: ./back  # Portainer ira dans le dossier /back chercher le Dockerfile
    container_name: azur_back
    ports:
      - "8081:8080"
    depends_on:
      - db-immo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-immo:5432/azurimmo
      SPRING_DATASOURCE_USERNAME: co_lelong
      SPRING_DATASOURCE_PASSWORD: Clelong@Post.2026
    networks:
      - immo_network

  front-immo:
    build:
      context: ./front # Portainer ira dans le dossier /front
    container_name: azur_front
    ports:
      - "8082:80"
    depends_on:
      - back-immo
    networks:
      - immo_network

networks:
  immo_network:
    driver: bridge

volumes:
  azur_data:
