# URL : On utilise le nom du service Docker "db-immo" défini dans ton YAML
spring.datasource.url=jdbc:postgresql://db-immo:5432/azurimmo
spring.datasource.username=co_lelong
spring.datasource.password=Clelong@Post.2026

# Driver et Dialect pour PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pour que Hibernate crée les tables tout seul au démarrage
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
